# Form implementation generated from reading ui file 'c:\Python\mukku_workspace\Election Form 3D_E Generator\ui\main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(589, 515)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 9, 531, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(85, 255, 127);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 15px 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(31, 80, 531, 138))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox.setStyleSheet("padding: 5px 5px;\n"
"border-radius: 10px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.selectFormTypeLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.selectFormTypeLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectFormTypeLabel.setFont(font)
        self.selectFormTypeLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.selectFormTypeLabel.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.selectFormTypeLabel.setScaledContents(False)
        self.selectFormTypeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.selectFormTypeLabel.setWordWrap(False)
        self.selectFormTypeLabel.setObjectName("selectFormTypeLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.selectFormTypeLabel)
        self.formTypeComboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formTypeComboBox.sizePolicy().hasHeightForWidth())
        self.formTypeComboBox.setSizePolicy(sizePolicy)
        self.formTypeComboBox.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.formTypeComboBox.setFont(font)
        self.formTypeComboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px 10px;\n"
"}\n"
"")
        self.formTypeComboBox.setObjectName("formTypeComboBox")
        self.formTypeComboBox.addItem("")
        self.formTypeComboBox.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.formTypeComboBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Save Configuration"))
        self.comboBox.setItemText(0, _translate("Form", "-- Select Constituencies --"))
        self.comboBox.setItemText(1, _translate("Form", "9-Barfung"))
        self.comboBox.setItemText(2, _translate("Form", "10-Poklok-Kamrang"))
        self.comboBox.setItemText(3, _translate("Form", "11-Namchi-Singhithang"))
        self.comboBox.setItemText(4, _translate("Form", "12-Melli"))
        self.comboBox.setItemText(5, _translate("Form", "13-Namthang-Rateypanni"))
        self.comboBox.setItemText(6, _translate("Form", "14-Temi-Namphing"))
        self.comboBox.setItemText(7, _translate("Form", "15-Rangang-Yangang"))
        self.selectFormTypeLabel.setText(_translate("Form", "Select Form Type : "))
        self.formTypeComboBox.setItemText(0, _translate("Form", "Form 3D"))
        self.formTypeComboBox.setItemText(1, _translate("Form", "Form 3E"))
